server:
  port: 11000

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.21.128:3306/mall_wms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: mall-ware
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  rabbitmq:
    host: 192.168.21.128
    port: 5672
    virtual-host: /
    listener:
      simple:
        # 手动确认接受消息
        acknowledge-mode: manual
    password: guest
    username: guest

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
logging:
  level:
    com.wff: debug

myRabbitmq:
  MQConfig:
    queues: stock.release.stock.queue
    delayQueue: stock.delay.queue
    eventExchange: stock-event-exchange
    routingKey: stock.locked
    letterRoutingKey: stock.release
    # 库存自动过期时间 单位:(毫秒)
    ttl: 120000
