server:
  port: 10000

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.21.128:3306/mall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: mall-product

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  thymeleaf:
    cache: false

  redis:
    host: 192.168.21.128
    port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 3600000
      use-key-prefix: true
#      key-prefix: CACHE_
      cache-null-values: true

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: 1
      logic-not-delete-value: 0

logging:
  level:
    com.wff.mall: error


#  feign.client.config.default.read-timeout=600000
#  feign.client.config.default.connect-timeout=600000
#feign:
#  client:
#    config:
#      default:
#        read-timeout: 600000
#        connect-timeout: 600000

