spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: 123456
      secret-key: 123456
      oss:
        endpoint: 123456
        bucket: 123456

  application:
    name: mall-third-party

server:
  port: 30000
