spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      sms:
        host: 111111
        path: 111111
        appcode: 111111
      access-key: 111111
      secret-key: 111111
      oss:
        endpoint: 111111
        bucket: 111111

  application:
    name: mall-third-party

server:
  port: 30000
