spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      sms:
        host: https://dfsns.market.alicloudapi.com
        path: /data/send_sms
        appcode: 33a43c3e45a545d99a160b407ebeaedb
      access-key: LTAI5tNzPYZC9ZL9DKyRroMm
      secret-key: evlWPp0lzbf3W8tGLqGW62IPuRyBEn
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
        bucket: mall-wff

  application:
    name: mall-third-party

server:
  port: 30000
