server:
  port: 9000

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.21.128:3306/mall_oms
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  application:
    name: mall-order

  rabbitmq:
    host: 192.168.21.128
    port: 5672
    # 指定虚拟主机
    virtual-host: /
    username: guest
    password: guest
    # 开启发送端确认
    publisher-confirm-type: correlated
    #　开启发送端消息抵达队列确认
    publisher-returns: true
    # 只要抵达队列，以异步优先回调我们这个 returnconfirm
    template:
      mandatory: true
    # 手动ack消息 消息不容易丢失
    listener:
      simple:
        acknowledge-mode: manual

  thymeleaf:
    cache: false

  session:
    store-type: redis

  redis:
    host: 192.168.21.128
    port: 6379
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss

myRabbitmq:
  queue: mall-queue
  exchange: mall-exchange
  routeKey: mall
  MQConfig:
    # 订单队列
    queues: order.release.order.queue
    delayQueue: order.delay.queue
    eventExchange: order-event-exchange
    routingKey: order.release.order
    createOrder: order.create.order
    # 订单自动过期时间 单位:(毫秒)
    ttl: 60000
    # 库存解锁队列
    ReleaseOther: stock.release.stock.queue
    ReleaseOtherKey: order.release.other
    password: guest
    username: guest
mall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

alipay:
  app_id: 2021000117669585
  # 支付宝异步回调通知 这个来感应订单是否完成
  notify_url: http://4o0113122k.qicp.vip/payed/notify
  return_url: http://member.mall.com/memberOrder.html
  timeout: 15m